### ISSUE TITLE
ModuleNotFoundError: No module named 'mmdet'

### ISSUE THREAD

**Issue by Sairam13001** [csuhan/ReDet#110]
I followed all the steps in install.md and installed ReDet

When I try to run train.py with DOTA dataset, I get the following error:

**Traceback (most recent call last):
  File "/home/ai20resch13001/ReDet-dota/tools/train.py", line 6, in <module>
    from mmdet import __version__
ModuleNotFoundError: No module named 'mmdet'**

Please help me with this issue. Is this issue because of the environment? 

I am using a linux system and I used the below line of command while installing ReDet

**conda install pytorch=1.3.1 torchvision cudatoolkit=10.0 -c pytorch -y**

And I am using mmcv == 0.4.3

**Comment by yuan-kai-design** [comment]
Do you solve this error:"No module named 'mmdet'"
