### ISSUE TITLE
Cost of time? How long will it take with a single 1080ti gpu?

### ISSUE THREAD

**Issue by TheRealPoseidon** [csuhan/ReDet#113]
In Redet, the ReResNet backbone is trained with 100 epochs. How long will it take? (with single 1080ti gpu?)

**Comment by csuhan** [comment]
ReR50 with 8 V100, fp32 takes about 7 days.
So, it will be a long time with single 1080ti.

**Comment by TheRealPoseidon** [comment]
thanks a lot
