### ISSUE TITLE
旋转框解码问题

### ISSUE THREAD

**Issue by zhangcongzc** [csuhan/ReDet#119]
您好，您在训练及测试时多次使用delta2dbbox对旋转框进行解码，但使用的函数版本不一样，delta2dbbox, v2, v3三个版本并且它们只在角度解码有差别，我想请问您这样设计的理由是什么呢?　什么时候选择什么版本又是如何确定的呢？

**Comment by csuhan** [comment]
它们的x, y, angle的解码方式不同，我们实现了几种典型的bbox编解码方式。版本选择完全是根据实验结果确定的。
