### ISSUE TITLE
模型输出的旋转框坐标超出了图片的边界

### ISSUE THREAD

**Issue by hot-dog** [csuhan/ReDet#122]
您好，我使用自己的数据在您提供的DOTA预训练模型上进行finetune，得到的模型在测试的时候发现模型输出的坐标超出了图片的边界，甚至还有很多负数的坐标，看代码的实现模型输出的坐标应该是已经变换到原图片size上的，想请教下这个可能是什么原因呢？

**Comment by csuhan** [comment]
如果有少量的超出的边界框，属于正常现象；
如果有大量的错误预测，建议检查预训练权重加载是否正确

**Comment by hot-dog** [comment]
感谢回复，问题原因找到了，可能是跟我图片的格式和大小有关，我的图片是tif格式，并且大小跟模型输入不一样。我用opencv将图片重新保存成jpg并且resize到模型输入大小，结果就正常了。
