### ISSUE TITLE
标注框4个点的顺序

### ISSUE THREAD

**Issue by hot-dog** [csuhan/ReDet#123]
您好，请教下如果用自己的数据来做数据集进行训练的话，旋转标注框的4个点要按照什么顺序来排列呢？

**Comment by csuhan** [comment]
我们默认以object左上角的点(接近图像原点)为起始点。我们还提供了坐标重排序的算法：
https://github.com/csuhan/ReDet/blob/0b9addf3c2734659fd6ffc7824f2e659fde4419c/DOTA_devkit/dota_utils.py#L289-L317

**Comment by hot-dog** [comment]
感谢回复，我按照您上面的坐标重排序重新规整下数据，再训练看看效果。
