### ISSUE TITLE
No predictions for container-crane class in DOTA-1.5

### ISSUE THREAD

**Issue by Sairam13001** [csuhan/ReDet#124]
I trained the model on DOTA_1.5

When I ran test.py, the model did not return any predictions for a class 'container-crane'.

This class is added newly in DOTA_1.5 and was not present in DOTA_1.0

I used "configs/ReDet/ReDet_re50_refpn_1x_dota15.py"  as the config file for both training and testing and I double checked that the data path for trainval and test datasets is given correctly.

I can't understand why the model is not  predicting any object corresponding to this 'container-crane' class.

If someone has any thoughts on this, please let me know.

**Comment by csuhan** [comment]
I guess you check the folder `work_dirs/ReDet_re50_refpn_1x_dota15/results_xx_nms`, and find noting in `container-crane.txt`.
As container-crane has rather few instances in both training and testing sets, the model can hardly detect any objects of container-crane.
