### ISSUE TITLE
PREPARE DOTA 1.0 DATASET

### ISSUE THREAD

**Issue by Sairam13001** [csuhan/ReDet#128]
I downloaded the DOTA 1.0 dataset and there are 2812 training images in it.

 I used the DOTA_devkit/prepare_dota1.py for converting the data to COCO format.

After conversion, there are 21406 images. 

Is this how it works? Or am I doing something wrong?

Please let me know.

Thank you.

**Comment by csuhan** [comment]
Yes, there should be 21406 training images.

**Comment by Sairam13001** [comment]
Thank you for your reply. 

I trained ReDet model on DOTA 1.0. I used the same hyper parameters as given in the paper. But I could not get the mAP (76.25) as stated in the paper. 

I could only get 74.8 

Could you kindly suggest what I might be missing.

Thank you.

**Comment by csuhan** [comment]
Make sure you prepare the dataset and annotations with https://github.com/csuhan/ReDet/blob/master/DOTA_devkit/prepare_dota1.py

Also, check our training log to see the difference https://drive.google.com/file/d/1OXgenH6YvtyRUwPH8h9f9p9tBCh60Kln/view

Moreover, please re-run the training step as the variance of mAP exists in DOTA.

**Comment by Sairam13001** [comment]
Sure, thank you so much for the reply.
