### ISSUE TITLE
RuntimeError   in:  mmdet/core/anchor/anchor_target.py

### ISSUE THREAD

**Issue by Randomless** [csuhan/ReDet#15]
RuntimeError: Expected object of scalar type Byte but got scalar type Bool for argument #2

in:  mmdet/core/anchor/anchor_target.py

```python
def anchor_inside_flags(flat_anchors, valid_flags, img_shape,
                        allowed_border=0):
    img_h, img_w = img_shape[:2]
    allowed_border=-1
    if allowed_border >= 0:
        inside_flags = valid_flags & \
            (flat_anchors[:, 0] >= -allowed_border) & \
            (flat_anchors[:, 1] >= -allowed_border) & \
            (flat_anchors[:, 2] < img_w + allowed_border) & \
            (flat_anchors[:, 3] < img_h + allowed_border)
    else:
        inside_flags = valid_flags
    return inside_flags
```

**Comment by csuhan** [comment]
https://github.com/open-mmlab/mmdetection/issues/3587

**Comment by zf020114** [comment]
if allowed_border >= 0:
        inside_flags = valid_flags & \
                       (flat_anchors[:, 0] >= -allowed_border).type(torch.uint8) & \
                       (flat_anchors[:, 1] >= -allowed_border).type(torch.uint8) & \
                       (flat_anchors[:, 2] < img_w + allowed_border).type(torch.uint8) & \
                       (flat_anchors[:, 3] < img_h + allowed_border).type(torch.uint8)
