### ISSUE TITLE
Imgs_per_gpu and workers_per_gpu

### ISSUE THREAD

**Issue by Sairam13001** [csuhan/ReDet#157]
Could you kindly let me know the relation between imgs_per_gpu and workers_per_gpu. 

I have access to bigger GPUs. Could I use imgs_per_gpu = 8 and workers_per_gpu = 8 to fasten the experiments?

I know that Batch size =  (imgs_per_gpu * no._of_gpus) 

Could you kindly let me know about workers_per_gpu.

**Comment by csuhan** [comment]
Yes. If you have enough GPU memory, you can use imgs_per_gpu = 8 and workers_per_gpu = 8.

**Comment by Sairam13001** [comment]
Okay, thank you.
