### ISSUE TITLE
train

### ISSUE THREAD

**Issue by liminyu-web** [csuhan/ReDet#16]
hello~~~i want to ask why the size of the model I trained is about 257M, It's more than twice the size of the model on the website~

My training orders are: bash ./tools/dist_train.sh configs/ReDet/ReDet_re50_refpn_1x_dota15.py 4

**Comment by csuhan** [comment]
https://github.com/csuhan/ReDet/blob/44825e60a9ac7adc2aa84783982f1955fdf9740e/tools/publish_model.py#L17-L19

**Comment by liminyu-web** [comment]
Thank you for your reply！！！！ i have another question :  why  did i use this weight file of 257M to detect but the inference speed faster~~~

**Comment by csuhan** [comment]
The speed should be same as we load it once only in the beginning.
