### ISSUE TITLE
The model and loaded state dict do not match exactly

### ISSUE THREAD

**Issue by lyccol** [csuhan/ReDet#17]
你好，我完全按照:
Hello, I follow exactly: 
Please refer to [INSTALL.md](https://github.com/csuhan/ReDet/blob/master/INSTALL.md) for installation and dataset preparation.

Please see [GETTING_STARTED.md](https://github.com/csuhan/ReDet/blob/master/GETTING_STARTED.md) for the basic usage.

操作到
Operation to 
`python tools/test.py configs/ReDet/ReDet_re50_refpn_1x_dota15.py \
    work_dirs/ReDet_re50_refpn_1x_dota15/ReDet_re50_refpn_1x_dota15-7f2d6dda.pth \ 
    --out work_dirs/ReDet_re50_refpn_1x_dota15/results.pkl`
之后
after that 

出现了错误
Something went wrong

在执行tools/test.py
While executing tools/test.py 

`model = build_detector(cfg.model, train_cfg=None, test_cfg=cfg.test_cfg)`

的时候报错如下：
The error is reported as follows: 

(redet) root@liuyi:~/Documents/ReDet-master# python tools/test.py configs/ReDet/ReDet_re50_refpn_1x_dota15.py work_dirs/ReDet_re50_refpn_1x_dota15/ReDet_re50_refpn_1x_dota15-7f2d6dda.pth --out work_dirs/ReDet_re50_refpn_1x_dota15/results.pkl
ReResNet Orientation: 8	Fix Params: False
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
/opt/conda/conda-bld/pytorch_1573049310284/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1573049310284/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1573049310284/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
**The model and loaded state dict do not match exactly**

missing keys in source state_dict: backbone.layer3.2.conv3.filter, backbone.layer3.4.conv3.filter, backbone.layer4.2.conv3.filter, backbone.layer2.3.conv2.filter, neck.lateral_convs.3.conv.expanded_bias, neck.fpn_convs.1.conv.expanded_bias, neck.fpn_convs.2.conv.expanded_bias, neck.fpn_convs.3.conv.filter, backbone.layer3.2.conv2.filter, backbone.layer4.0.conv1.filter, backbone.layer2.1.conv2.filter, backbone.layer3.3.conv2.filter, backbone.layer4.0.conv3.filter, backbone.layer2.0.conv3.filter, backbone.layer3.5.conv2.filter, backbone.layer2.0.downsample.0.filter, backbone.layer3.4.conv2.filter, backbone.layer4.0.downsample.0.filter, backbone.layer4.1.conv3.filter, backbone.layer2.0.conv1.filter, backbone.layer3.3.conv3.filter, backbone.layer2.2.conv1.filter, backbone.layer2.1.conv3.filter, backbone.layer3.0.conv2.filter, backbone.layer2.0.conv2.filter, backbone.conv1.filter, backbone.layer3.2.conv1.filter, neck.lateral_convs.1.conv.filter, neck.fpn_convs.3.conv.expanded_bias, backbone.layer4.0.conv2.filter, backbone.layer3.0.conv3.filter, backbone.layer2.2.conv2.filter, neck.lateral_convs.0.conv.expanded_bias, neck.fpn_convs.1.conv.filter, backbone.layer4.2.conv1.filter, backbone.layer3.1.conv1.filter, backbone.layer2.3.conv1.filter, neck.lateral_convs.2.conv.expanded_bias, neck.lateral_convs.3.conv.filter, neck.lateral_convs.0.conv.filter, backbone.layer4.1.conv2.filter, backbone.layer3.5.conv1.filter, backbone.layer2.2.conv3.filter, backbone.layer4.2.conv2.filter, backbone.layer2.3.conv3.filter, neck.lateral_convs.1.conv.expanded_bias, backbone.layer3.3.conv1.filter, neck.fpn_convs.0.conv.expanded_bias, backbone.layer3.1.conv3.filter, neck.lateral_convs.2.conv.filter, neck.fpn_convs.2.conv.filter, backbone.layer3.1.conv2.filter, backbone.layer4.1.conv1.filter, backbone.layer3.5.conv3.filter, backbone.layer2.1.conv1.filter, neck.fpn_convs.0.conv.filter, backbone.layer3.0.downsample.0.filter, backbone.layer3.0.conv1.filter, backbone.layer3.4.conv1.filter

completed: 0, elapsed: 0s
writing results to work_dirs/ReDet_re50_refpn_1x_dota15/results.pkl

But I have put ReDet_re50_refpn_1x_dota15-7f2d6dda.pth in the correct position. 
How can I solve it? 
**--------------------------------------------------------环境-------------------------------------------------------------**
torch           1.3.1
torchvision     0.4.2
mmcv            0.2.13
mmdet           0.6.0+unknown       /root/Documents/ReDet-master

and
Package         Version             Location
--------------- ------------------- ----------------------------
addict          2.4.0
certifi         2020.12.5
cffi            1.14.5
chardet         4.0.0
cycler          0.10.0
Cython          0.29.23
e2cnn           0.1.7
idna            2.10
kiwisolver      1.3.1
matplotlib      3.4.1
mkl-fft         1.3.0
mkl-random      1.2.1
mkl-service     2.3.0
mmcv            0.2.13
mmdet           0.6.0+unknown       /root/Documents/ReDet-master
numpy           1.20.1
olefile         0.46
opencv-python   4.5.1.48
pandas          1.2.4
Pillow          8.2.0
pip             21.0.1
pycocotools     2.0.2
pycparser       2.20
pyparsing       3.0.0b2
python-dateutil 2.8.1
pytz            2021.1
PyYAML          5.4.1
requests        2.25.1
scipy           1.6.3
setuptools      52.0.0.post20210125
Shapely         1.8a1
six             1.15.0
terminaltables  3.1.0
torch           1.3.1
torchvision     0.4.2
tqdm            4.60.0
urllib3         1.26.4
wheel           0.36.2

**Comment by lyccol** [comment]
不好意思  解决了 是我没匹配好

**Comment by chandlerbing65nm** [comment]
@lyccol what was the solution? I also encountered this issue.

**Comment by gengyanlei** [comment]
@lyccol 
请问你是如何匹配的，我的也遇到了这个问题

**Comment by Varun221** [comment]
@lyccol @chandlerbing65nm @csuhan 
What was the solution? I am facing the same issue.
