### ISSUE TITLE
test.py文件中 The model and loaded state dict do not match exactly

### ISSUE THREAD

**Issue by HsLOL** [csuhan/ReDet#22]
我的权重与配置文件与**GETTING_STARTED.md**相同，而且源代码会将权重文件的路径自动设置在tools/configs下，我又拷贝出来一份放在了tools/configs下面，但是会出现模型尺寸不匹配的错误。

The model and loaded state dict do not match exactly

missing keys in source state_dict: backbone.layer4.2.conv3.filter, neck.lateral_convs.3.conv.filter, backbone.layer2.0.downsample.0.filter, backbone.layer3.0.conv2.filter, backbone.layer3.0.conv3.filter, neck.lateral_convs.2.conv.filter, backbone.layer4.1.conv3.filter, neck.lateral_convs.1.conv.filter, backbone.layer3.1.conv1.filter, neck.fpn_convs.0.conv.expanded_bias, backbone.layer2.3.conv2.filter, neck.fpn_convs.1.conv.expanded_bias, backbone.layer4.0.downsample.0.filter, backbone.layer3.4.conv3.filter, backbone.layer3.5.conv2.filter, neck.lateral_convs.0.conv.expanded_bias, backbone.layer2.1.conv3.filter, backbone.layer3.2.conv1.filter, backbone.layer3.5.conv1.filter, backbone.layer3.2.conv2.filter, neck.fpn_convs.2.conv.filter, backbone.layer4.1.conv1.filter, backbone.layer3.2.conv3.filter, backbone.layer4.2.conv2.filter, neck.lateral_convs.2.conv.expanded_bias, backbone.layer4.1.conv2.filter, neck.lateral_convs.0.conv.filter, backbone.layer3.3.conv2.filter, neck.lateral_convs.3.conv.expanded_bias, neck.fpn_convs.2.conv.expanded_bias, backbone.layer2.0.conv2.filter, neck.fpn_convs.1.conv.filter, backbone.layer4.0.conv1.filter, backbone.layer3.5.conv3.filter, backbone.layer3.0.conv1.filter, backbone.layer3.1.conv3.filter, backbone.layer2.0.conv3.filter, backbone.layer2.2.conv1.filter, backbone.layer4.0.conv2.filter, backbone.layer3.3.conv3.filter, backbone.layer3.3.conv1.filter, neck.fpn_convs.3.conv.filter, backbone.layer4.2.conv1.filter, backbone.layer2.2.conv2.filter, backbone.layer3.4.conv1.filter, neck.fpn_convs.3.conv.expanded_bias, backbone.layer4.0.conv3.filter, backbone.layer3.1.conv2.filter, backbone.layer2.3.conv3.filter, backbone.layer2.1.conv1.filter, neck.lateral_convs.1.conv.expanded_bias, backbone.layer2.1.conv2.filter, neck.fpn_convs.0.conv.filter, backbone.layer2.3.conv1.filter, backbone.layer3.0.downsample.0.filter, backbone.layer2.0.conv1.filter, backbone.layer2.2.conv3.filter, backbone.layer3.4.conv2.filter, backbone.conv1.filter

[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 6/6, 4.5 task/s, elapsed: 1s, ETA:     0s
writing results to /home/user/code/ReDet-master/work_dirs/ReDet_re50_refpn_1x_dota15/results.pkl

**Comment by csuhan** [comment]
`.filter`是模型加载后自动生成的，因此是正常的提示。

**Comment by HsLOL** [comment]
> `.filter`是模型加载后自动生成的，因此是正常的提示。

好的，谢谢~
