### ISSUE TITLE
The test time is more than 11 hours!

### ISSUE THREAD

**Issue by gongh4** [csuhan/ReDet#23]
Dir sir!
         Thanks for your great jobs!
         I have ran your test code with the corresponding weights and the mAP is correct on dota1.0/task1 (mAP=80.03).
         However, the test time is more than 11 hours with GPU 1080ti.
         Do you have any suggestions?

**Comment by csuhan** [comment]
Yeah, It's slow for two reasons:
* Large mounts of multi-scale testing samples.
* We use `rotate_aug` for testing which is not well optimized.

**Comment by liminyu-web** [comment]
hello~~sir!  I also have this question，i have run the multi-scale test code on DOTAv1.5 , it took more than a day to complete the test，i also run the single-scale code on DOTAv1.5，it also took a lot of time.
I would like to ask what is the specific reason for the slow test, and I have tried to modify the confidence and IOU threshold, but nothing worked. 
Do you have any suggestions~~,thank you !

**Comment by liminyu-web** [comment]
hello,  sir! I also have this question，i have run the multi-scale test code on DOTAv1.5 , it took more than a day to complete the test，i also run the single-scale code on DOTAv1.5，it also took a lot of time.
I would like to ask what is the specific reason for the slow test, and I have tried to modify the confidence and IOU threshold, but nothing worked.
Do you have any suggestions,  thank you !
