### ISSUE TITLE
Required bbox AP

### ISSUE THREAD

**Issue by nishit01** [csuhan/ReDet#24]
Hi @csuhan, thanks for open-sourcing the code
I needed bbox AP but unable to figure out how to achieve that. I saw tools/coco_eval.py is something related to that but still not able to get it correctly 

Can you guide me on how to get bbox AP for the trainval_split data for DOTAv1 dataset (as I think testing bbox mAP is not achievable considering the test evaluation is done on DOTA evaluation server, that only provides class mAP)

Looking forward for your reply ... thanks

**Comment by csuhan** [comment]
Copy from https://github.com/csuhan/ReDet/blob/master/GETTING_STARTED.md

```
#Assume that you have already downloaded the checkpoints to work_dirs/.

# run test
python tools/test.py configs/ReDet/ReDet_re50_refpn_1x_dota15.py \
    work_dirs/ReDet_re50_refpn_1x_dota15/ReDet_re50_refpn_1x_dota15-7f2d6dda.pth \ 
    --out work_dirs/ReDet_re50_refpn_1x_dota15/results.pkl

# Parse the results.pkl to the format needed for DOTA evaluation
python tools/parse_results.py --config configs/ReDet/ReDet_re50_refpn_1x_dota15.py --type OBB

```

Finally, run eval with https://github.com/csuhan/ReDet/blob/master/DOTA_devkit/dota_v15_evaluation_task1.py

**Comment by Znc1996** [comment]
imagesetfile: Text file containing the list of images, one image per line

Is there any code to generate it?

**Comment by csuhan** [comment]
@Znc1996 
Create `generate_label.sh` with the content:
```bash
#!/bin/sh
path=your_path_to_image_dir
files=$(ls $path)
for filename in $files
do
  echo ${filename%.*} >>imageset.txt
done
```
Then run `bash generate_label.sh`
