### ISSUE TITLE
ImportError: cannot import name 'get_dataset'

### ISSUE THREAD

**Issue by mathshangw** [csuhan/ReDet#26]
i tried to train the model but got this error 

 `from mmdet.datasets import get_dataset `

`ImportError: cannot import name 'get_dataset'`

i also run `sh compile.sh`  and `pip3 install setup.py`  but error still

**Comment by csuhan** [comment]
run `pip list` to see whether mmdet is installed.

I suggest to install this repo with:
```bash
bash compile.sh && python setup.py develop
```

**Comment by mathshangw** [comment]
Thanks but i got 
bash compile.sh
`Building roi align op...
compile.sh: line 6: cd: mmdet/ops/roi_align: No such file or directory
Traceback (most recent call last):
  File "setup.py", line 83, in <module>
    write_version_py()
  File "setup.py", line 72, in write_version_py
    with open(version_file, 'w') as f:
IOError: [Errno 2] No such file or directory: 'mmdet/version.py'
Building roi pool op...
compile.sh: line 13: cd: ../roi_pool: No such file or directory
Traceback (most recent call last):
  File "setup.py", line 83, in <module>
    write_version_py()`

**Comment by csuhan** [comment]
Please make sure your current dir is: `some_path/ReDet/`

**Comment by mathshangw** [comment]
Thanks for replying .. now i got the problem with cuda as i have 11.0 and searched for a solution.
i need to change AT_Check to TORCH_CHECK but in which files i should ?

**Comment by csuhan** [comment]
Please search all `.cu` and `.cpp` in `mmdet/ops`

**Comment by mathshangw** [comment]
I did it but got
from .bbox import bbox_overlaps_cython I importError: Path/ReDet/mmdet/core/bbox/bbox.so: undefined symbol: _Py_ZeroStruct
And stuck in this error above

The version I'm using is python3

**Comment by csuhan** [comment]
Try to delete previous `build`

**Comment by mathshangw** [comment]
Appreciate your reply.  But how can I delete it ?

**Comment by csuhan** [comment]
You can try to delete `bbox/build` and `bbox/*.so`

**Comment by mathshangw** [comment]
i tried it but got 
`from .bbox import bbox_overlaps_cython
ModuleNotFoundError: No module named 'mmdet.core.bbox.bbox'`

i tried also to install setup.py again but error exists .. appreciate your time for help .. Thanks

**Comment by mathshangw** [comment]
i got 
 `f'{obj_type} is not in the {registry.name} registry')
KeyError: 'ReDet is not in the models registry'`

**Comment by mathshangw** [comment]
excuse me does this error from the mmcv ? or i missed something ? 

Thanks in advance
