### ISSUE TITLE
 results.pkl问题

### ISSUE THREAD

**Issue by Znc1996** [csuhan/ReDet#30]
您好，打搅您了
请问处理hrsc2016数据集的results.pkl结果的代码是哪个呀?
Parse the results.pkl to the format needed for DOTA evaluation

**Comment by csuhan** [comment]
You need run `parse_results.py` first, then run `hrsc_evaluation.py` with proper settings:
https://github.com/csuhan/ReDet/blob/0b9addf3c2734659fd6ffc7824f2e659fde4419c/DOTA_devkit/hrsc2016_evaluation.py#L275-L278

**Comment by luoz66** [comment]
> 您好，打搅您了
> 请问处理hrsc2016数据集的results.pkl结果的代码是哪个呀?
> Parse the results.pkl to the format needed for DOTA evaluation

您好，请问您的问题解决了吗，我也有这个问题

**Comment by luoz66** [comment]
> parse_results.py

您好，运行parse_results.py解析HSRC2016生成的pkl的时候会出错
