### ISSUE TITLE
请问cascade mask rcnn的旋转目标检测的代码是哪个。

### ISSUE THREAD

**Issue by lyccol** [csuhan/ReDet#31]
您好：
请问cascade mask rcnn的旋转目标检测的代码是哪个。

另外想问一下配置文件中的h-obb代表什么意思。例如configs/DOTA1_5/faster_rcnn_h-obb_r50_fpn_1x_dota1_5.py中的h-obb是什么意思。

**Comment by csuhan** [comment]
https://github.com/dingjiansw101/AerialDetection
