### ISSUE TITLE
Is there any way to improve the speed of the test？

### ISSUE THREAD

**Issue by liminyu-web** [csuhan/ReDet#32]
hello, sir! ！I  have run the multi-scale test code on DOTAv1.5 , it took more than a day to complete the test，and i also run the single-scale code on DOTAv1.5，it also took a lot of time.
I would like to ask which structure has the most influence in the network and what is the specific reason for the slow test, and I have tried to modify the confidence and IOU threshold, but nothing worked.
Do you have any suggestions, thank you , sir !!!!!!

**Comment by csuhan** [comment]
For single-scale DOTA-v1.5, it just takes few minutes on 4 V100/Tian X.
For multi-scale, it indeed takes more time for some reasons:
* the number of multi-scale images.
* python implementation of [e2cnn](https://github.com/QUVA-Lab/e2cnn) rather than C/Cuda.
