### ISSUE TITLE
为什么我训练自己的数据集在work_dir目录中没产生.pth文件，却只有.log文件？

### ISSUE THREAD

**Issue by youchen2020** [csuhan/ReDet#34]
![image](https://user-images.githubusercontent.com/66814800/123049933-af557a00-d432-11eb-8ae7-6a130f9cc05c.png)
loss都能正常下降，但是每个epoch训练后并没有产生checkpoint的.pth文件，log却记录的很清晰，能回答一下吗，谢谢。
我的命令行是这样的：CUDA_VISIBLE_DEVICES=2 python tools/train.py /work/plane_code/ReDet/configs/ReDet/ReDet_re50_refpn_1x_dota15_ms.py --work_dir /work/checkpoint/new__pkl --validate

**Comment by csuhan** [comment]
Please change `interval` to 1 to storage the checkpoint of each epoch.

https://github.com/csuhan/ReDet/blob/0b9addf3c2734659fd6ffc7824f2e659fde4419c/configs/ReDet/ReDet_re50_refpn_1x_dota15_ms.py#L195

**Comment by youchen2020** [comment]
> Please change `interval` to 1 to storage the checkpoint of each epoch.
> 
> https://github.com/csuhan/ReDet/blob/0b9addf3c2734659fd6ffc7824f2e659fde4419c/configs/ReDet/ReDet_re50_refpn_1x_dota15_ms.py#L195
谢谢！！！
