### ISSUE TITLE
多GPU测试的一个小问题

### ISSUE THREAD

**Issue by gongh4** [csuhan/ReDet#35]
你好,我使用sh文件中的多GPU测试的命令行进行测试,想要加快测试速度,毕竟一张卡的多尺度测试有点慢..

测试使用了两张显卡,测试过程没有任何问题. 但是当所有的图片测试完成之后(测试进度条走完), 其中一张卡就会不再运行程序(显存占用为0), 而另外一张卡的显存依旧在占用. 最终的results.pkl文件始终生成不出来, 程序就卡住.

这个过程反复测试了3次,每次都遇到这种情况.

当我采用一张卡进行测试, 运行test.py的时候都很正常, 可以正常的生成results.pkl文件

请问您是否遇到这种情况..

万分感谢!

**Comment by csuhan** [comment]
我没有遇到过这个问题，建议在下面代码中加断点查看卡在什么地方：
https://github.com/csuhan/ReDet/blob/0b9addf3c2734659fd6ffc7824f2e659fde4419c/tools/test.py#L47-L67
