### ISSUE TITLE
how to define the angle in the Rotated RoI Align?

### ISSUE THREAD

**Issue by lianglele185** [csuhan/ReDet#36]
First of all, thank you very much for publicing code. I have some questions about the Rotated RoI Align module. The rroi is expressed as (x,y,w,h,angle), how is angle defined here, I can't understand the angle defined in the polygonToRotRectangle_batch function?

**Comment by lzed2399** [comment]
RRoI module can predict the angle

**Comment by csuhan** [comment]
@lianglele185 The same as [RoITrans](https://arxiv.org/abs/1812.00155)
