### ISSUE TITLE
does this code work well with cuda 11.1 and rtx2060?

### ISSUE THREAD

**Issue by SamMohel** [csuhan/ReDet#38]
thanks for your effort and sharing the code .. excuse me i have problems in setup the project in 2060 rtx with cuda 11.1 trying to do all solved issues but cannot run the train.py file

**Comment by csuhan** [comment]
#1

**Comment by SamMohel** [comment]
Thanks a lot for replying but i don't have folder ops in mmdet

**Comment by csuhan** [comment]
Please follow our [install giude](https://github.com/csuhan/ReDet/blob/master/INSTALL.md)
