### ISSUE TITLE
ReResNet 预训练问题

### ISSUE THREAD

**Issue by zhangcongzc** [csuhan/ReDet#42]
请问为什么已经加载了您ReResNet的预训练模型，还会出现不匹配问题呢？

2021-07-05 20:38:56,774 - INFO - load model from: work_dirs/ReResNet_pretrain/re_resnet50_c8_batch256-25b16846.pth
2021-07-05 20:38:56,790 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: head.fc.weight, head.fc.bias

missing keys in source state_dict: layer4.2.conv1.filter, layer1.1.conv1.filter, layer3.0.downsample.0.filter, layer1.0.conv2.filter, layer3.0.conv3.filter, layer4.1.conv3.filter, layer1.0.conv1.filter, layer3.3.conv1.filter, layer2.2.conv1.filter, layer3.3.conv3.filter, layer3.1.conv3.filter, layer3.4.conv1.filter, layer3.5.conv2.filter, layer2.1.conv2.filter, layer2.0.downsample.0.filter, layer2.1.conv1.filter, layer3.2.conv3.filter, layer4.2.conv3.filter, layer3.0.conv1.filter, layer3.4.conv2.filter, layer2.3.conv2.filter, layer3.0.conv2.filter, layer4.0.conv2.filter, layer2.0.conv3.filter, layer3.2.conv2.filter, layer4.0.downsample.0.filter, layer3.5.conv1.filter, layer4.2.conv2.filter, layer2.0.conv2.filter, layer2.2.conv3.filter, layer1.2.conv2.filter, layer2.2.conv2.filter, layer3.3.conv2.filter, layer2.3.conv1.filter, layer2.1.conv3.filter, layer1.0.downsample.0.filter, layer3.5.conv3.filter, conv1.filter, layer4.1.conv1.filter, layer4.1.conv2.filter, layer4.0.conv3.filter, layer1.1.conv2.filter, layer4.0.conv1.filter, layer1.2.conv3.filter, layer2.0.conv1.filter, layer3.4.conv3.filter, layer3.1.conv1.filter, layer1.2.conv1.filter, layer1.0.conv3.filter, layer3.1.conv2.filter, layer1.1.conv3.filter, layer3.2.conv1.filter, layer2.3.conv3.filter

**Comment by csuhan** [comment]
https://github.com/csuhan/ReDet/issues/22

**Comment by zhangcongzc** [comment]
好的，谢谢
