### ISSUE TITLE
您好！！请问re_resnet-101和152能否提供预训练模型？

### ISSUE THREAD

**Issue by liminyu-web** [csuhan/ReDet#44]
您好，我在re_resnet.py文件中看到了101和152的backbone，请问~这两种情况可以提供预训练模型吗？精度可以达到多少呢？谢谢！！

**Comment by hukaixuan19970627** [comment]
同求

**Comment by hukaixuan19970627** [comment]
另外还想问下作者，Redet训练2×/3×的话精度还能继续提高吗

**Comment by csuhan** [comment]
ReR50在8张V100预训练大概需要3-7天，因此我们并没有101和152的预训练

**Comment by csuhan** [comment]
@hukaixuan19970627 可以尝试train from scratch，效果与预训练应该类似

**Comment by hukaixuan19970627** [comment]
> @hukaixuan19970627 可以尝试train from scratch，效果与预训练应该类似

好的，train from scratch的话那在DOTA上大概多少个epoch比较合适呢

**Comment by csuhan** [comment]
> > @hukaixuan19970627 可以尝试train from scratch，效果与预训练应该类似
> 
> 好的，train from scratch的话那在DOTA上大概多少个epoch比较合适呢

默认是1x，可以尝试3x等
