### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by qixiong-wang** [csuhan/ReDet#49]
Thanks for your work, csuhan.
I try to use your code on my server with 3090, which only support cuda 11.  So I follow the instruction of [https://github.com/csuhan/ReDet/issues/1](url) with pytorch 1.7.0 and cuda 11.0.
But when I run the `bash compile.sh`, I met a problem as follow:
/usr/local/cuda-11.0/bin/nvcc -I/home/wangqx/anaconda3/envs/redet_torch17_py38/lib/python3.8/site-packages/torch/include -I/home/wangqx/anaconda3/envs/redet_torch17_py38/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/wangqx/anaconda3/envs/redet_torch17_py38/lib/python3.8/site-packages/torch/include/TH -I/home/wangqx/anaconda3/envs/redet_torch17_py38/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.0/include -I/home/wangqx/anaconda3/envs/redet_torch17_py38/include/python3.8 -c -c /home/wangqx/airplane_detection_qx/ReDet_torch17_py38/mmdet/ops/roi_pool/src/roi_pool_kernel.cu -o /home/wangqx/airplane_detection_qx/ReDet_torch17_py38/mmdet/ops/roi_pool/build/temp.linux-x86_64-3.8/src/roi_pool_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=roi_pool_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
nvcc fatal   : Unsupported gpu architecture 'compute_86'

Then I use the command `TORCH_CUDA_ARCH_LIST=7.0 bash compile.sh` to solve this problem. But the code still can not work and raise this this error:

 File "/home/wangqx/airplane_detection_qx/ReDet_torch17_py38/mmdet/apis/inference.py", line 66, in inference_detector
    return _inference_single(model, imgs, img_transform, device)
  File "/home/wangqx/airplane_detection_qx/ReDet_torch17_py38/mmdet/apis/inference.py", line 93, in _inference_single
    result = model(return_loss=False, rescale=True, **data)
  File "/home/wangqx/anaconda3/envs/redet_torch17_py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wangqx/airplane_detection_qx/ReDet_torch17_py38/mmdet/models/detectors/base_new.py", line 97, in forward
    return self.forward_test(img, img_meta, **kwargs)
  File "/home/wangqx/airplane_detection_qx/ReDet_torch17_py38/mmdet/models/detectors/base_new.py", line 86, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/wangqx/airplane_detection_qx/ReDet_torch17_py38/mmdet/models/detectors/ReDet.py", line 239, in simple_test
    proposal_list = self.simple_test_rpn(
  File "/home/wangqx/airplane_detection_qx/ReDet_torch17_py38/mmdet/models/detectors/test_mixins.py", line 12, in simple_test_rpn
    proposal_list = self.rpn_head.get_bboxes(*proposal_inputs)
  File "/home/wangqx/airplane_detection_qx/ReDet_torch17_py38/mmdet/models/anchor_heads/anchor_head.py", line 216, in get_bboxes
    proposals = self.get_bboxes_single(cls_score_list, bbox_pred_list,
  File "/home/wangqx/airplane_detection_qx/ReDet_torch17_py38/mmdet/models/anchor_heads/rpn_head.py", line 92, in get_bboxes_single
    proposals, _ = nms(proposals, cfg.nms_thr)
  File "/home/wangqx/airplane_detection_qx/ReDet_torch17_py38/mmdet/ops/nms/nms_wrapper.py", line 49, in nms
    inds = nms_cuda.nms(dets_th, iou_thr)
RuntimeError: CUDA error: no kernel image is available for execution on the device

**Comment by csuhan** [comment]
First, I suggest to upgrade your pytorch version, like pytorch1.8. See https://github.com/pytorch/pytorch/issues/49161
After that, you need to modify related ops. See https://github.com/csuhan/ReDet/issues/1

Then the code may run successfully, or failed. If it fails, you need to modify several lines in Pytorch. (I can't remember exactly, but I have run the code in 3090 and win.)

**Comment by lyccol** [comment]
I tried that method, but I still get this error.
running develop
running egg_info
writing mmdet.egg-info/PKG-INFO
writing dependency_links to mmdet.egg-info/dependency_links.txt
writing requirements to mmdet.egg-info/requires.txt
writing top-level names to mmdet.egg-info/top_level.txt
reading manifest file 'mmdet.egg-info/SOURCES.txt'
writing manifest file 'mmdet.egg-info/SOURCES.txt'
running build_ext
building 'mmdet.ops.nms.soft_nms_cpu' extension
Emitting ninja build file /root/Documents/s2anet/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2
g++ -pthread -shared -B /root/anaconda3/envs/s2anet/compiler_compat -L/root/anaconda3/envs/s2anet/lib -Wl,-rpath=/root/anaconda3/envs/s2anet/lib -Wl,--no-as-needed -Wl,--sysroot=/ /root/Documents/s2anet/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/soft_nms_cpu.o -o build/lib.linux-x86_64-3.7/mmdet/ops/nms/soft_nms_cpu.cpython-37m-x86_64-linux-gnu.so
g++: error: /root/Documents/s2anet/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/soft_nms_cpu.o: No such file or directory
error: command 'g++' failed with exit status 1

**Comment by qixiong-wang** [comment]
I update the pytorch version to 1.8.0 and the error still exist. 
Is it feasible to integrate the code into mmdet V2?

**Comment by qixiong-wang** [comment]
> First, I suggest to upgrade your pytorch version, like pytorch1.8. See [pytorch/pytorch#49161](https://github.com/pytorch/pytorch/issues/49161)
> After that, you need to modify related ops. See #1
> 
> Then the code may run successfully, or failed. If it fails, you need to modify several lines in Pytorch. (I can't remember exactly, but I have run the code in 3090 and win.)
Hi, csuhan. I wonder how to modify code in Pytorch?

**Comment by qixiong-wang** [comment]
> Then the code may run successfully, or failed. If it fails, you need to modify several lines in Pytorch. (I can't remember exactly, but I have run the code in 3090 and win.)

Hi, csuhan. I wonder how to modify code in Pytorch?

**Comment by qixiong-wang** [comment]
I solve this problem by compiling the compile.sh in the following instruction
`TORCH_CUDA_ARCH_LIST=8.0 bash compile.sh `

**Comment by nicolefinnie** [comment]
It works for pytorch 1.7 if we compile with `TORCH_CUDA_ARCH_LIST=7.0`, thanks for your solution, it was a nasty bug to find.
