### ISSUE TITLE
cannot import name'deform_conv_cuda'错误

### ISSUE THREAD

**Issue by lingblessing** [csuhan/ReDet#5]
在运行 python tools/test.py ${CONFIG_FILE} ${CHECKPOINT_FILE} [--out ${RESULT_FILE}] 这条语句的时候，显示错误：ImportError: cannot import name 'deform_conv_cuda'，请问楼主该怎么解决呢，已经执行过pip install deform_conv_cuda和setup.py develop

**Comment by csuhan** [comment]
请先编译cuda扩展
```
bash compile.sh
```

**Comment by lingblessing** [comment]
当我编译bash compile.sh时，显示错误src/poly_nms_cuda.cpp:3:23: error: ‘AT_CHECK’ was not declared in this scope  #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")，最终报错为error: command 'gcc' failed with exit status 1
百度说将AT_CHECK函数更改为TORCH_CHECK，解决办法是用pytorch1.5，这个只能用pytorch1.1-1.3，请问楼主该怎么解决呢

**Comment by csuhan** [comment]
The same as #1. Two solutions to solve it:
1. Try lower version Pytorch, e.g., Pytorch==1.3.1
2. Replace all `AT_CHECK` with `TORCH_CHECK` and re-compile.
