### ISSUE TITLE
Hello,my data set has only horizontal box and no mask information. Can I use this method?

### ISSUE THREAD

**Issue by lesleyping** [csuhan/ReDet#50]
My dataset has only horizontal box and no mask information. Can I use ReDet ?
thanks

**Comment by csuhan** [comment]
Yes, but you need to generate coco's format annotation with the `segmentation` filled by your horizontal bounding box, i.e. put `x1,y1,x2,y2,...,x4,y4` in the `segmentation`.

While, we have not test its performance on HBB as it can not demonstrate our rotation equivariance.
