### ISSUE TITLE
关于RIRoIAlign的问题

### ISSUE THREAD

**Issue by kuazhangxiaoai** [csuhan/ReDet#51]
请问，看了您的论文，关于RIRoIAlign模块，是根据特征图不同的角度，在各个channel中生成对应角度的结果，然后再把channel进行排序，对吗？最后的channel是输入的8倍，对吗？我没看到关于特征图的旋转或者是channel的排序。
这段代码看不太懂，ind_float,是什么呢？
![image](https://user-images.githubusercontent.com/54108453/126435428-e0e7b44a-351d-4209-814b-ce6e56315d4e.png)

**Comment by csuhan** [comment]
> 关于RIRoIAlign模块，是根据特征图不同的角度，在各个channel中生成对应角度的结果，然后再把channel进行排序，对吗？

特征图已经包含各个角度的结果，我们要做的是排序和插值。

> 最后的channel是输入的8倍，对吗？

和输入channel一致

> 我没看到关于特征图的旋转或者是channel的排序。

排序：
https://github.com/csuhan/ReDet/blob/0b9addf3c2734659fd6ffc7824f2e659fde4419c/mmdet/ops/riroi_align/src/riroi_align_kernel.cu#L112-L116
插值：
https://github.com/csuhan/ReDet/blob/0b9addf3c2734659fd6ffc7824f2e659fde4419c/mmdet/ops/riroi_align/src/riroi_align_kernel.cu#L155

> 这段代码看不太懂，ind_float,是什么呢？

ind_float: RRoI角度/360，ind：RRoI对应feature maps的orientation channel， l_var, r_var：插值的距离系数

**Comment by kuazhangxiaoai** [comment]
这个theta是弧度制的输入，不是角度制的吧？我看并没有转换啊？谢谢
![image](https://user-images.githubusercontent.com/54108453/126444480-baf3eac3-8976-4839-aa9b-6988d6c3ce90.png)

**Comment by csuhan** [comment]
Refer to:

https://github.com/csuhan/ReDet/blob/0b9addf3c2734659fd6ffc7824f2e659fde4419c/mmdet/ops/riroi_align/src/riroi_align_kernel.cu#L5

https://github.com/csuhan/ReDet/blob/0b9addf3c2734659fd6ffc7824f2e659fde4419c/mmdet/ops/riroi_align/src/riroi_align_kernel.cu#L102

**Comment by kuazhangxiaoai** [comment]
是的，就是这里，有点儿看不懂，看上去thelta的输入是弧度制，为什么选择弧度制作为输入形式呢？

**Comment by csuhan** [comment]
因为上一阶段的prediction输出弧度
