### ISSUE TITLE
置信度过高问题

### ISSUE THREAD

**Issue by liliwannian** [csuhan/ReDet#52]
您好，使用您的代码用在我的数据集（特点：背景很大）上，在训练时我把没有目标的图像也加进去训练了，测试结果中在背景上有很多误报，而且误报的目标框的置信度特别高。请问出现这种情况的原因是什么？该怎么解决？

**Comment by csuhan** [comment]
* 建议把这部分图像去除
* 检查数据是否有问题、模型是否收敛
