### ISSUE TITLE
关于评估时测试集标签问题

### ISSUE THREAD

**Issue by xiao-pang6** [csuhan/ReDet#53]
在DOTA_devkit文件夹的dota_v15_evaluation_task1.py中
annopath = r'data/dota15/test/dota1_5_labelTxt/{:s}.txt'
    imagesetfile = r'data/dota15/test/testset.txt'
原始数据集中没有标签文件，请问您是否可以提供

**Comment by csuhan** [comment]
请提交测评服务器
