### ISSUE TITLE
在DOTA evaluation server上的问题

### ISSUE THREAD

**Issue by xiao-pang6** [csuhan/ReDet#54]
总是报如下错误：
There is something wrong with your submission as follows:
/root/DOAI_server/media/submits_task1/Task1_results_nms
You can submit standard formatted results again
我是按照步骤生成的Task1_results文件，不知道错在哪里

**Comment by csuhan** [comment]
请注意提交的zip不能包含目录

**Comment by zqwang21** [comment]
> 总是报如下错误： There is something wrong with your submission as follows: /root/DOAI_server/media/submits_task1/Task1_results_nms You can submit standard formatted results again 我是按照步骤生成的Task1_results文件，不知道错在哪里

请问你后来是怎么解决这个问题，我也是报了这个错误。【但我提交的zip里面没有包含目录，里面直接就是txt。】
