### ISSUE TITLE
About RPN

### ISSUE THREAD

**Issue by heizie** [csuhan/ReDet#57]
Thanks for your work.
I've noticed: 'We first adopt the rotation-equivariant backbone to extract rotation-equivariant features, followed by an RPN and RoI Transformer (RT)'
But in your[ config file](https://github.com/csuhan/ReDet/blob/ca252f2752a49634e7edf322df144cf588cfece1/configs/ReDet/ReDet_re50_refpn_1x_dota15.py), you are using `class RPNHead`. But I can't find where you implement the transformer?

btw. the `class RPNHeadRbbox' is for the RRPN? (https://arxiv.org/pdf/1703.01086.pdf)

**Comment by csuhan** [comment]
RPN(RPNHead) and RoI Transoformer(SharedFCBBoxHeadRbbox)
https://github.com/csuhan/ReDet/blob/0b9addf3c2734659fd6ffc7824f2e659fde4419c/configs/ReDet/ReDet_re50_refpn_1x_dota1.py#L17-L47

> the `class RPNHeadRbbox' is for the RRPN?

`RPNHeadRbbox` is a temp version of RRPN, we do not suggest to use it.

**Comment by heizie** [comment]
> RPN(RPNHead) and RoI Transoformer(SharedFCBBoxHeadRbbox)
> https://github.com/csuhan/ReDet/blob/0b9addf3c2734659fd6ffc7824f2e659fde4419c/configs/ReDet/ReDet_re50_refpn_1x_dota1.py#L17-L47
> 
> > the `class RPNHeadRbbox' is for the RRPN?
> 
> `RPNHeadRbbox` is a temp version of RRPN, we do not suggest to use it.

I've read a lot from that project in these days. I think if we want the rbox, we need to define the ROI Transformer from line 17 - line 66 right?
https://github.com/csuhan/ReDet/blob/0b9addf3c2734659fd6ffc7824f2e659fde4419c/configs/ReDet/ReDet_re50_refpn_1x_dota1.py#L17-L66

so basically, if I'm right, you've only used your own rotation-equivariant backbone and FPN in this config?

Thanks again for saving a lot of time for us
