### ISSUE TITLE
demo_large_image.py error

### ISSUE THREAD

**Issue by zyt0203** [csuhan/ReDet#6]
when I use the commend "python demo_large_image.py"  DOTA dataset , I meet the follow error,how I can do to solve it. Thank you!
Traceback (most recent call last):
  File "/home/zyt/PycharmProjects/ReDet-master/demo_large_image.py", line 149, in <module>
    roitransformer.inference_single_vis(img_path, out_path, (1024, 1024), (3072, 3072))
NameError: name 'roitransformer' is not defined
P2714__1__3513___1426.png

**Comment by csuhan** [comment]
fixed by https://github.com/csuhan/ReDet/commit/1555a487177a88b9b0f6578edd36e20d1f53216c

**Comment by zyt0203** [comment]
Thanks for your replay! With your help,I solving the problem!
