### ISSUE TITLE
多尺度训练测试

### ISSUE THREAD

**Issue by zhangcongzc** [csuhan/ReDet#65]
您在论文里说"we prepare multi-scale data at three scales {0.5, 1.0, 1.5}, and random rotation for training and testing."
对于多尺度训练，您好似构建了一个多尺度的数据集而不是使用mmdet常规的方式，我猜测您的方式如下：将数据分别裁成512*512，1024*1024，1536*1536构建新数据集，训练时全部resize成1024*1024。
1.这样做与设置img_scale=[(512, 512), (1024, 1024), (1536, 1536)], multiscale_mode='value', resize_keep_ratio=True, 有什么区别吗？前者效果更好？
2.您使用的mmdet版本为0.6.0，好似无法使用上述mmdet常规方式进行多尺度测试，请问您是如何进行多尺度测试的呢？
希望得到您指点。

**Comment by csuhan** [comment]
数据生成方式：https://github.com/csuhan/ReDet/blob/master/DOTA_devkit/prepare_dota1_5_v2.py

这里的多尺度指的是：首先将一张图像缩放到指定scale，然后再切成1024的patch进行训练。

1. 先缩放再切成patch会考虑不同patch之间的重叠，生成样本更多
2. 现在多尺度图像上测试，然后将测试结果合并。参考：https://github.com/csuhan/ReDet/blob/master/tools/parse_results.py

**Comment by zhangcongzc** [comment]
感谢您！问题已解决
