### ISSUE TITLE
关于数据增强方法的问题

### ISSUE THREAD

**Issue by kuazhangxiaoai** [csuhan/ReDet#66]
请问，您使用的数据增强方法都有哪些呢？mAP几乎能提高的10个点左右，尤其是那个CC的类别能从9提到50左右。
谢谢

**Comment by csuhan** [comment]
* multi-scale at (0.5, 1.0, 1.5)
* random rotation training and testing

**Comment by kuazhangxiaoai** [comment]
> * multi-scale at (0.5, 1.0, 1.5)
> * random rotation training and testing

那您数据增强后，epoach设置成多少了呢？

**Comment by csuhan** [comment]
12 epochs
