### ISSUE TITLE
关于evaluate问题

### ISSUE THREAD

**Issue by 1994su** [csuhan/ReDet#68]
我用tools/test.py生成了result.pkl文件，然后通过parse_result解析了结果，请问如何评估结果输出定量指标？ 如果采用DOTA_Devkit中的dota_v15_evaluation_task1.py测试，切割数据集的时候并没有test的真值labelTxt，无法评估。请问如何才能输出定量指标呢？还请不吝赐教，多谢

**Comment by csuhan** [comment]
> Parse the results.pkl to the format needed for DOTA evaluation: https://captain-whu.github.io/DOTA/evaluation.html

You need to submit the result to online evaluation server.
