### ISSUE TITLE
ReR50-ReFPN   The model and loaded state dict do not match exactly

### ISSUE THREAD

**Issue by mmoghadam11** [csuhan/ReDet#70]
ReResNet Orientation: 8	Fix Params: False
loading annotations into memory...
Done (t=1.74s)
creating index...
index created!
The model and loaded state dict do not match exactly

missing keys in source state_dict: neck.fpn_convs.3.conv.expanded_bias, backbone.layer3.2.conv1.filter, neck.fpn_convs.0.conv.filter, backbone.layer3.1.conv3.filter, neck.fpn_convs.1.conv.filter, backbone.layer3.4.conv2.filter, backbone.layer3.5.conv1.filter, neck.lateral_convs.1.conv.expanded_bias, backbone.layer2.1.conv1.filter, neck.fpn_convs.2.conv.expanded_bias, backbone.layer2.3.conv2.filter, backbone.layer4.0.downsample.0.filter, backbone.layer4.1.conv1.filter, backbone.layer3.5.conv2.filter, backbone.layer4.1.conv3.filter, backbone.layer4.0.conv2.filter, backbone.layer3.1.conv2.filter, backbone.layer3.4.conv1.filter, neck.lateral_convs.3.conv.filter, backbone.layer3.3.conv2.filter, neck.fpn_convs.2.conv.filter, backbone.layer3.2.conv2.filter, neck.fpn_convs.1.conv.expanded_bias, backbone.layer2.2.conv1.filter, backbone.layer2.3.conv1.filter, backbone.layer3.2.conv3.filter, backbone.layer2.2.conv2.filter, backbone.layer4.2.conv3.filter, backbone.layer3.0.downsample.0.filter, backbone.layer4.2.conv2.filter, backbone.layer2.0.conv3.filter, backbone.layer2.1.conv3.filter, backbone.layer2.0.conv2.filter, backbone.conv1.filter, neck.fpn_convs.3.conv.filter, backbone.layer2.0.downsample.0.filter, neck.lateral_convs.0.conv.filter, backbone.layer2.2.conv3.filter, backbone.layer2.0.conv1.filter, backbone.layer4.1.conv2.filter, backbone.layer4.0.conv1.filter, backbone.layer3.0.conv3.filter, backbone.layer3.3.conv3.filter, backbone.layer4.0.conv3.filter, neck.lateral_convs.1.conv.filter, backbone.layer3.4.conv3.filter, neck.fpn_convs.0.conv.expanded_bias, backbone.layer3.0.conv1.filter, backbone.layer2.1.conv2.filter, neck.lateral_convs.0.conv.expanded_bias, neck.lateral_convs.2.conv.expanded_bias, backbone.layer2.3.conv3.filter, backbone.layer3.5.conv3.filter, neck.lateral_convs.3.conv.expanded_bias, backbone.layer3.0.conv2.filter, backbone.layer3.1.conv1.filter, backbone.layer3.3.conv1.filter, neck.lateral_convs.2.conv.filter, backbone.layer4.2.conv1.filter

why???what should i do???

**Comment by csuhan** [comment]
https://github.com/csuhan/ReDet/issues/22

**Comment by mmoghadam11** [comment]
> #22

tnx 👍 
so its ok
but i test it an i got very low AP result for dota v1 : 
This is your result for task 1:

mAP: 0.3796692927779224
ap of each class: plane:0.5393134760132164, baseball-diamond:0.2727272727272727, bridge:0.4428214528237172, ground-track-field:0.14898989898989898, small-vehicle:0.2509144865918008, large-vehicle:0.25942160410103354, ship:0.7073533101735577, tennis-court:0.5454545454545455, basketball-court:0.32725572697522204, storage-tank:0.09090909090909091, soccer-ball-field:0.21752528974341798, roundabout:0.14793388429752066, harbor:0.6952776159604523, swimming-pool:0.6333621700100804, helicopter:0.41577956689800866

why??
