### ISSUE TITLE
关于用自己的无人机航拍图像数据集训练，请教几个问题

### ISSUE THREAD

**Issue by zyzjly** [csuhan/ReDet#73]
1、训练数据是否用DOTA的标注工具比较好，哪里能获得类似工具；
2、

**Comment by csuhan** [comment]
DOTA采用的标注工具
https://github.com/dingjiansw101/LabelTool

**Comment by zyzjly** [comment]
请问这个工具可以直接用吗，是否需要适应性改造？我准备训练的数据并不在DOTA数据集的类别中

**Comment by zyzjly** [comment]
2、我目前的训练数据，一个图片对应一个Json文件，是否需要将这些json文件整合后才能直接用ReDet进行训练

**Comment by csuhan** [comment]
https://github.com/dingjiansw101/LabelTool/blob/8abe7e0771d0444379dc188cf2428d997e7ec2da/LabelTool.html#L163-L170

**Comment by zyzjly** [comment]
您好，请问关于LabelTool有使用说明吗？是直接打开LabelTool.html进行标注吗？我试用LabelTool工具，可加载图片，但无法分类标注、保存标注信息。

**Comment by csuhan** [comment]
* 把图片放入对应文件夹
* 运行`run.bat`
* 使用**IE**打开LabelTool.html

**Comment by zyzjly** [comment]
谢谢，我用您们提供的软件标注数据时，不知道怎么打类别标签，能否指导一下？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "csuhan/ReDet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月18日(星期三) 晚上10:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [csuhan/ReDet] 关于用自己的无人机航拍图像数据集训练，请教几个问题 (#73)





  
把图片放入对应文件夹
 
运行run.bat
 
使用IE打开LabelTool.html
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
