### ISSUE TITLE
训练时没有做数据增强吗？

### ISSUE THREAD

**Issue by 1994su** [csuhan/ReDet#96]
您好，我看代码训练设置中只设置了flip_ratio，并没有设置其他的增强增强方式？请问这块可以增加数据增强方式吗

**Comment by csuhan** [comment]
没有设置数据增强。
可以使用增强，如multi-scale, random crop, random rotate

**Comment by 1994su** [comment]
> 没有设置数据增强。
> 可以使用增强，如multi-scale, random crop, random rotate

您的Redet很多是经过修改了的，比如输入训练集数据时采用的是get_dataset，而不是mmdet默认的build_datasets,这样没法直接使用pipeline，我看custom代码中CustomDataset类中定义了一些增强方法，请问我该如何加到里面呢？

**Comment by 1994su** [comment]
> > 没有设置数据增强。
> > 可以使用增强，如multi-scale, random crop, random rotate
> 
> 您的Redet很多是经过修改了的，比如输入训练集数据时采用的是get_dataset，而不是mmdet默认的build_datasets,这样没法直接使用pipeline，我看custom代码中CustomDataset类中定义了一些增强方法，请问我该如何加到里面呢？

我在mmdet/dataset/utils.py中加入 from mmdet.dataset import CustomDataset 或者from .custom import CustomDataset都会报错，cannot import name ‘CustomDataset’ from 'mmdet.datasets'，这就很奇怪，明明custom跟他们就在同一个文件夹下，还请指教一下，麻烦了

**Comment by csuhan** [comment]
我们使用的mmdet版本是比较早的，建议参考早期的版本（may be Jan 2019？）
关于CustomDataset，我暂时没有遇到这样的问题，建议重新检查代码安装等。

**Comment by 1994su** [comment]
> 我们使用的mmdet版本是比较早的，建议参考早期的版本（may be Jan 2019？）
> 关于CustomDataset，我暂时没有遇到这样的问题，建议重新检查代码安装等。

上述问题我已经解决，目前在进行多尺度的时候出现了问题。将img_scale设置为[(512,512),(1024,1024)],利用get_dataset读入数据，如果设置了多尺度，那么会调用transforms_rrbox的方法gt_mask_bp_obbs_list，将标签转为gt_obb，但是进行多尺度，也就是resize成512时，图片和标签会缩小，这样就会出现mask2poly_single中检测不到标签mask的轮廓，利用minAreaRect无法获取poly造成报错，请问这个问题遇到过吗，也就是解决多尺度数据及标签输入问题。

**Comment by csuhan** [comment]
会存在这样的问题。因此我们的多尺度数据都是先进行多尺度的缩放，然后裁剪，而不是先裁剪，然后online缩放。

如果仍需要这样做，那么你需要在dataloader里首先筛选出哪些annotation不能被`gt_mask_bp_obbs_list`识别，然后将筛选后的annotation进行训练。

**Comment by 1994su** [comment]
> 会存在这样的问题。因此我们的多尺度数据都是先进行多尺度的缩放，然后裁剪，而不是先裁剪，然后online缩放。
> 
> 如果仍需要这样做，那么你需要在dataloader里首先筛选出哪些annotation不能被`gt_mask_bp_obbs_list`识别，然后将筛选后的annotation进行训练。

ok ，感谢大佬指导
